
import React, { useState, useEffect } from 'react';
import { StartupPlan } from '../types';

interface PlanDashboardProps {
  plan: StartupPlan;
  onCheckReadiness: () => void;
}

const PlanDashboard: React.FC<PlanDashboardProps> = ({ plan, onCheckReadiness }) => {
  const storageKey = `founderpilot-progress-${plan.name.replace(/\s+/g, '-').toLowerCase()}`;
  
  const [checkedItems, setCheckedItems] = useState<Record<string, boolean>>(() => {
    const saved = localStorage.getItem(storageKey);
    return saved ? JSON.parse(saved) : {};
  });

  useEffect(() => {
    localStorage.setItem(storageKey, JSON.stringify(checkedItems));
  }, [checkedItems, storageKey]);

  const toggleItem = (key: string) => {
    setCheckedItems(prev => ({ ...prev, [key]: !prev[key] }));
  };

  const handleExport = () => {
    const content = `# ${plan.name} - Official Pitch Deck Structure\n\n` +
      `**Tagline:** ${plan.elevatorPitch}\n` +
      `**Initial Readiness:** ${plan.readinessScore}/100\n\n` +
      `## 1. The Problem (Indian Context)\n${plan.problem}\n\n` +
      `## 2. Target Persona\n- **Role:** ${plan.persona.role}\n- **Pain Point:** ${plan.persona.primaryPainPoint}\n\n` +
      `## 3. MVP Core (Must Have)\n${plan.mvpFeatures.mustHave.join('\n- ')}\n\n` +
      `## 4. Execution Roadmap (Next 7 Days)\n${plan.roadmap.map(r => `Day ${r.day}: ${r.task}`).join('\n')}\n\n` +
      `## 5. GTM Strategy\n${plan.acquisitionStrategy}\n\n` +
      `---\nGenerated by FounderPilot AI - Student Founder Edition`;

    const element = document.createElement("a");
    const file = new Blob([content], {type: 'text/plain'});
    element.href = URL.createObjectURL(file);
    element.download = `${plan.name.replace(/\s+/g, '_')}_MasterPlan.md`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  const SectionHeader: React.FC<{ title: string; icon: React.ReactNode }> = ({ title, icon }) => (
    <div className="flex items-center space-x-3 mb-6">
      <div className="p-2.5 bg-indigo-500/10 text-indigo-400 rounded-xl border border-indigo-500/20">
        {icon}
      </div>
      <h2 className="text-2xl font-black text-white tracking-tight">{title}</h2>
    </div>
  );

  return (
    <div className="max-w-7xl mx-auto py-12 px-4 space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-700">
      
      {/* Top Banner */}
      <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
        <div className="lg:col-span-3 glass rounded-[2.5rem] p-8 md:p-12 border-white/10 relative overflow-hidden">
          <div className="absolute top-0 left-0 w-2 h-full bg-indigo-500"></div>
          <div className="flex flex-col md:flex-row justify-between gap-8">
            <div className="flex-1">
              <div className="flex items-center space-x-3 mb-4">
                <span className="bg-cyan-500/10 text-cyan-400 text-[10px] font-black tracking-widest uppercase px-3 py-1 rounded-full border border-cyan-500/20">Roadmap Generated</span>
              </div>
              <h1 className="text-5xl font-black text-white mb-4 tracking-tighter leading-none">{plan.name}</h1>
              <p className="text-xl text-slate-400 font-medium italic mb-8 italic">"{plan.elevatorPitch}"</p>
              
              <div className="grid grid-cols-1 md:grid-cols-2 gap-8 border-t border-white/5 pt-8">
                <div>
                  <h3 className="text-[10px] font-black text-slate-500 uppercase tracking-widest mb-3">Campus Context</h3>
                  <p className="text-slate-300 font-medium">{plan.problem}</p>
                </div>
                <div>
                  <h3 className="text-[10px] font-black text-slate-500 uppercase tracking-widest mb-3">Initial Target</h3>
                  <p className="text-slate-100 font-bold">{plan.targetAudience}</p>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Readiness CTA - The New Tool */}
        <div className="glass rounded-[2.5rem] p-8 flex flex-col items-center justify-center text-center border-indigo-500/20 bg-indigo-500/10 relative group cursor-pointer" onClick={onCheckReadiness}>
          <div className="absolute inset-0 bg-indigo-500/10 opacity-0 group-hover:opacity-100 transition-opacity"></div>
          <div className="w-20 h-20 bg-indigo-600 rounded-full flex items-center justify-center mb-6 shadow-2xl group-hover:scale-110 transition-transform">
            <svg className="w-10 h-10 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M13 10V3L4 14h7v7l9-11h-7z" /></svg>
          </div>
          <h3 className="text-lg font-black text-white mb-2">Deep Readiness Test</h3>
          <p className="text-[10px] text-indigo-300 uppercase tracking-widest font-black mb-4">Stress-test this idea</p>
          <button className="text-[10px] font-black text-white bg-indigo-600 px-4 py-2 rounded-full uppercase tracking-widest">Start Analysis</button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        <div className="lg:col-span-2 space-y-8">
          
          <div className="glass rounded-3xl p-10 shadow-xl border-white/5">
            <SectionHeader 
              title="Target Persona" 
              icon={<svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" /></svg>} 
            />
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
              <div className="space-y-4">
                <div className="p-4 bg-white/5 rounded-2xl border border-white/5">
                  <span className="text-[10px] font-black text-indigo-400 uppercase tracking-widest block mb-1">Primary Role</span>
                  <p className="text-white font-bold">{plan.persona.role}</p>
                </div>
                <div className="p-4 bg-white/5 rounded-2xl border border-white/5">
                  <span className="text-[10px] font-black text-indigo-400 uppercase tracking-widest block mb-1">Hostel/Campus Habits</span>
                  <p className="text-slate-300 text-sm">{plan.persona.behavior}</p>
                </div>
              </div>
              <div className="space-y-4">
                <div className="p-4 bg-white/5 rounded-2xl border border-white/5">
                  <span className="text-[10px] font-black text-indigo-400 uppercase tracking-widest block mb-1">Launch Point</span>
                  <p className="text-white font-bold">{plan.persona.location}</p>
                </div>
                <div className="p-4 bg-indigo-500/10 rounded-2xl border border-indigo-500/20">
                  <span className="text-[10px] font-black text-indigo-400 uppercase tracking-widest block mb-1">Pain Point</span>
                  <p className="text-white font-bold italic">"{plan.persona.primaryPainPoint}"</p>
                </div>
              </div>
            </div>
          </div>

          <div className="glass rounded-3xl p-10 shadow-xl">
            <SectionHeader 
              title="7-Day Roadmap" 
              icon={<svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>} 
            />
            <div className="space-y-8">
              {plan.roadmap.map((step) => (
                <div key={step.day} className="flex group cursor-pointer" onClick={() => toggleItem(`day-${step.day}`)}>
                  <div className="mr-8 flex flex-col items-center">
                    <div className={`w-12 h-12 rounded-2xl flex items-center justify-center font-black text-lg transition-all border ${checkedItems[`day-${step.day}`] ? 'bg-indigo-500 text-white border-indigo-400' : 'bg-white/5 text-slate-500 border-white/10 group-hover:border-indigo-500'}`}>
                      {checkedItems[`day-${step.day}`] ? '✓' : step.day}
                    </div>
                    {step.day < 7 && <div className={`w-0.5 h-full mt-2 ${checkedItems[`day-${step.day}`] ? 'bg-indigo-500' : 'bg-white/5'}`}></div>}
                  </div>
                  <div className="pb-6">
                    <h4 className={`text-xl font-bold mb-1 ${checkedItems[`day-${step.day}`] ? 'text-indigo-400' : 'text-white'}`}>{step.task}</h4>
                    <p className="text-slate-400 text-sm italic">Goal: {step.goal}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>

        <div className="space-y-8">
          <div className="bg-gradient-to-br from-indigo-950 to-navy-900 border border-indigo-500/20 rounded-[2rem] p-8">
            <SectionHeader 
              title="Validation Checklist" 
              icon={<svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>} 
            />
            <div className="space-y-4">
              {plan.validationChecklist.map((task, idx) => (
                <div key={idx} className="flex items-start cursor-pointer group" onClick={() => toggleItem(`val-${idx}`)}>
                  <div className={`w-6 h-6 rounded-lg border-2 mt-0.5 mr-4 flex items-center justify-center shrink-0 transition-all ${checkedItems[`val-${idx}`] ? 'bg-indigo-500 border-indigo-500' : 'border-white/20'}`}>
                    {checkedItems[`val-${idx}`] && <span className="text-xs">✓</span>}
                  </div>
                  <span className={`text-sm ${checkedItems[`val-${idx}`] ? 'line-through opacity-40 text-slate-500' : 'text-slate-300'}`}>{task}</span>
                </div>
              ))}
            </div>
          </div>

          <div className="glass rounded-[2rem] p-8">
            <SectionHeader 
              title="Free Tool Stack" 
              icon={<svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M11 4a2 2 0 114 0v1a2 2 0 11-4 0V4zM11 13a2 2 0 114 0v1a2 2 0 11-4 0v-1z" /></svg>} 
            />
            <div className="space-y-4">
              {plan.toolStack.map((tool, idx) => (
                <div key={idx} className="p-4 bg-white/5 rounded-2xl border border-white/5">
                  <div className="flex justify-between mb-1">
                    <span className="font-black text-white text-xs">{tool.name}</span>
                    <span className="text-[8px] text-indigo-400 font-black uppercase">{tool.category}</span>
                  </div>
                  <p className="text-[10px] text-slate-500">{tool.reason}</p>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>

      <div className="flex justify-center pt-12">
        <button 
          onClick={handleExport}
          className="px-12 py-5 bg-indigo-600 text-white font-black rounded-2xl shadow-2xl hover:bg-indigo-500 transition-all active:scale-95 flex items-center"
        >
          <svg className="w-6 h-6 mr-3" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" /></svg>
          Export Master Execution Plan (.md)
        </button>
      </div>
    </div>
  );
};

export default PlanDashboard;
